# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches-ignore:
        - 'main'

  pull_request:
    branches-ignore: 
        - 'main'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  call-build:
      uses: ./.github/workflows/msbuild.yml  # 调用构建工作流
  
  create-action:
    runs-on: windows-latest
    needs: call-build  # 确保在构建完成后执行

    steps:        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: StackRestorer
        path: dist/
